# Generated by Django 4.1.13 on 2024-02-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('vpa', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
