# Generated by Django 4.1.13 on 2024-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymuseum', '0002_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
