# Generated by Django 4.1.13 on 2024-02-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymuseum', '0003_alter_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.CharField(default='rtkp', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='account_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='ifsc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='vpa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
