# Generated by Django 4.1.13 on 2024-02-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymuseum', '0004_userdetails_username_alter_userdetails_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminImmuseum',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status_flag', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='subscribers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('image_desc', models.TextField(null=True)),
                ('image_likes', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymuseum.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_flag', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_subscriptions', to='mymuseum.userdetails')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_to_subscriptions', to='mymuseum.userdetails')),
                ('subscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_subscriptions', to='mymuseum.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers_to', through='mymuseum.Subscribers', to='mymuseum.userdetails'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', through='mymuseum.Subscribers', to='mymuseum.userdetails'),
        ),
    ]
