# Generated by Django 4.1.13 on 2024-02-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymuseum', '0005_adminimmuseum_userdetails_status_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers_of', through='mymuseum.Subscribers', to='mymuseum.userdetails'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions_to', through='mymuseum.Subscribers', to='mymuseum.userdetails'),
        ),
        migrations.RemoveField(
            model_name='userimages',
            name='user_details',
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('commenter_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymuseum.userdetails')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymuseum.userimages')),
            ],
        ),
        migrations.AddField(
            model_name='userimages',
            name='user_details',
            field=models.ManyToManyField(related_name='images', to='mymuseum.userdetails'),
        ),
    ]
