# Generated by Django 4.1.13 on 2024-02-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymuseum', '0007_remove_usercomments_image_id_delete_userimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('image_desc', models.TextField(null=True)),
                ('image_likes', models.IntegerField(null=True)),
                ('status_flag', models.IntegerField(default=1)),
                ('user_details', models.ManyToManyField(related_name='images', to='mymuseum.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='usercomments',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymuseum.userimages'),
            preserve_default=False,
        ),
    ]
